name: obs_ctrl
description: Remote control for OBS.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  obs_websocket: ^2.3.1

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
