# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and Deploy
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    name: Build Apps
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - run: |
          flutter pub get
          flutter build apk --split-per-abi --build-number ${{ github.run_number }} --build-name ${GITHUB_REF:10}
          cd build/app/outputs/apk/release
          mv app-arm64-v8a-release.apk ${{ github.event.repository.name }}-${GITHUB_REF:10}-arm64-v8a.apk 
          mv app-armeabi-v7a-release.apk ${{ github.event.repository.name }}-${GITHUB_REF:10}-armeabi-v7a.apk 
          mv app-x86_64-release.apk ${{ github.event.repository.name }}-${GITHUB_REF:10}-x86_64.apk

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/apk/release/*.apk'